"""empty message

Revision ID: 4f31cc58b900
Revises: 38e37b901d16
Create Date: 2024-09-29 08:17:33.616060

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4f31cc58b900'
down_revision = '38e37b901d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moviepricing', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moviepricing', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
